export const NOT_ALLOWED_TAGS = ['style', 'link', 'script', 'meta', 'title', 'head'];

export const CONVERT_TAGS: Record<string, string> = {
  html: 'div',
  body: 'div',
};

// لیست پیش‌فرض attribute های مجاز
export const DEFAULT_ALLOWED_ATTRIBUTES = [
  'src',
  'href',
  'alt',
  'title',
  'colspan',
  'rowspan',
  'target',
  'rel',
  'type',
  'name',
  'value',
  'placeholder',
  'disabled',
  'readonly',
  'checked',
  'selected',
  'multiple',
  'min',
  'max',
  'step',
  'pattern',
  'required',
  'maxlength',
  'width',
  'height',
  // 'data-*',
  'aria-*',
  'role',

  //svg
  'xmlns',
  'viewBox',
];

// استایل‌هایی که معمولاً مفید هستند
export const USEFUL_STYLES = [
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-radius',
  'background',
  'background-color',
  'background-image',
  'background-size',
  'background-position',
  'color',
  'font-size',
  'font-weight',
  'font-family',
  'line-height',
  'text-align',
  'text-decoration',
  'text-transform',
  'letter-spacing',
  'word-spacing',
  'flex',
  'flex-direction',
  'flex-wrap',
  'justify-content',
  'align-items',
  'gap',
  'grid',
  'grid-template-columns',
  'grid-template-rows',
  'grid-gap',
  'overflow',
  'overflow-x',
  'overflow-y',
  'z-index',
  'opacity',
  'cursor',
  'transform',
  'transition',
  'animation',
  'box-shadow',
  'text-shadow',
];

// لیست CORS Proxy های عمومی
export const CORS_PROXIES = [
  'https://api.allorigins.win/raw?url=',
  'https://corsproxy.io/?',
  'https://cors-anywhere.herokuapp.com/',
];
